# Generated by Django 4.0.6 on 2022-07-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='poduct_name',
            new_name='product_name',
        ),
    ]
